### ISSUE TITLE
Wiki Link for Raspberry image seems to be broken

### ISSUE THREAD

**Issue by mueckinger** [QWaveSystems/QwaveSys-Raspberry-Pi-Package#2]
http://ftp.qwavesys.com/Qwave-Raspbian_qwavesys-rpi-003.img

**Comment by pamornthep** [comment]
Please download again with this link. I've changed the file format to .zip.

http://ftp.qwavesys.com/Qwave-Raspbian_qwavesys-rpi-003.zip
